### ISSUE TITLE
Is OneDay necessary?

### ISSUE THREAD

**Issue by forthesr** [forthesr/WildCats#12]
Since we have sleep to take off a day and it automatically goes to map after sleep (or it should), do we need OneDay?

**Comment by JordanLouie** [comment]
oneDay will also have the code for going from place to place, making sure playa goes to home when out of stamina, and choosing to go on dates, etc. I realized it doesn't need the line to substract a day just now

**Comment by JordanLouie** [comment]
Also, current working file of DatingSim is in Test folder.
