### ISSUE TITLE
Chat file name format

### ISSUE THREAD

**Issue by JordanLouie** [forthesr/WildCats#18]
All the chats need to be named the same way so we can call the files easily. 
-J's files are all capitalized, L's aren't, which way should we pick?
-rename Daphne's intro to DaphneIntro

**Comment by forthesr** [comment]
We can capitalize them

**Comment by JordanLouie** [comment]
Reminder to J: need to figure out naming files situation-just renaming them in computer didnt work
-check if it is really needed to work
