### ISSUE TITLE
Approach to Overlay, Appearance and Backgrounds

### ISSUE THREAD

**Issue by forthesr** [forthesr/WildCats#8]
Edited
Change all backgrounds to be a 20 x 3 String[][] array with each String taking up 20, 30, 20 characters respectively. 
Change all appearances to be a single 12 String[] array with each String taking up 30 characters

Write overlay to change the backgrounds [4][2] column downwards with appearances column (as discussed in class)

**Comment by forthesr** [comment]
Correction:
Strings will take up to 30 characters.

**Comment by forthesr** [comment]
Appearance will take up to String[12] max, current test is String[9]

**Comment by forthesr** [comment]
public String[][] overlay(String[][] place){

//for loop to go through String[][]
// replace String[r][f] with String[w][f]
}

datableSO.overlay(place)

**Comment by JordanLouie** [comment]
30 characters per seem too big
sample image for school was made using 20 X 3 2D array, 20 characters per string--> already looks big

**Comment by JordanLouie** [comment]
Overlay made in setting, should it be void? no point in returning something
